/**
 * Rebuilds packages/core/grammar/tree-sitter-migoto.wasm from a checkout of our
 * tree-sitter-migoto fork and records where it came from in grammar/SOURCE.json.
 *
 *   XXMI_GRAMMAR_SRC=../tree-sitter-migoto pnpm grammar:update [--allow-dirty]
 *
 * The checkout needs its dev dependencies installed (`npm ci`), for the tree-sitter CLI.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { copyFileSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const GRAMMAR_DIR = resolve(import.meta.dirname, '../packages/core/grammar');
const UPSTREAM = 'https://github.com/lupomikti/tree-sitter-migoto';

const args = process.argv.slice(2);
const allowDirty = args.includes('--allow-dirty');
const src = args.find((a) => !a.startsWith('--')) ?? process.env.XXMI_GRAMMAR_SRC;
if (!src) {
  console.error('usage: XXMI_GRAMMAR_SRC=<fork checkout> pnpm grammar:update [--allow-dirty]');
  process.exit(2);
}
const forkDir = resolve(src);

function run(cmd: string, cmdArgs: string[]): string {
  return execFileSync(cmd, cmdArgs, {
    cwd: forkDir,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
    shell: process.platform === 'win32',
  }).trim();
}

function gitOrNull(gitArgs: string[]): string | null {
  try {
    return run('git', gitArgs) || null;
  } catch {
    return null;
  }
}

if (!allowDirty && run('git', ['status', '--porcelain']) !== '') {
  console.error(`${forkDir} has uncommitted changes; commit them or pass --allow-dirty.`);
  process.exit(1);
}

const cli = join(forkDir, 'node_modules/.bin/tree-sitter');
if (!existsSync(cli) && !existsSync(`${cli}.cmd`)) {
  console.error(`tree-sitter CLI not found in ${forkDir}; run \`npm ci\` there first.`);
  process.exit(1);
}

const outWasm = join(GRAMMAR_DIR, 'tree-sitter-migoto.wasm');
console.log(`Building WASM from ${forkDir} …`);
run(cli, ['build', '--wasm', '-o', outWasm]);
copyFileSync(join(forkDir, 'LICENSE'), join(GRAMMAR_DIR, 'LICENSE.tree-sitter-migoto'));

const forkPackage = JSON.parse(readFileSync(join(forkDir, 'package.json'), 'utf8')) as {
  version: string;
};
const source = {
  note: 'Generated by scripts/update-grammar.ts. Do not edit by hand.',
  repository: gitOrNull(['remote', 'get-url', 'origin']),
  upstream: UPSTREAM,
  upstreamVersion: forkPackage.version,
  branch: gitOrNull(['rev-parse', '--abbrev-ref', 'HEAD']),
  commit: gitOrNull(['rev-parse', 'HEAD']),
  dirty: allowDirty && run('git', ['status', '--porcelain']) !== '',
  treeSitterCli: run(cli, ['--version']).replace(/^tree-sitter\s+/, ''),
  sha256: createHash('sha256').update(readFileSync(outWasm)).digest('hex'),
};
writeFileSync(join(GRAMMAR_DIR, 'SOURCE.json'), `${JSON.stringify(source, null, 2)}\n`);
console.log(`Wrote ${outWasm}\n${JSON.stringify(source, null, 2)}`);
